name: CI


on:

  push:
    branches: [ master ]

 
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    
    steps:
      
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false
      - name: RUN
        run: ${GITHUB_WORKSPACE}/docker_bash.sh
  
